# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/khalil/Projects/skype

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/khalil/Projects/skype

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /home/khalil/Projects/skype && $(CMAKE_COMMAND) -E cmake_progress_start /home/khalil/Projects/skype/CMakeFiles /home/khalil/Projects/skype/src/server/test_client//CMakeFiles/progress.marks
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/server/test_client/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/khalil/Projects/skype/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/server/test_client/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/server/test_client/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/server/test_client/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/khalil/Projects/skype && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/server/test_client/CMakeFiles/test_client.dir/rule:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/server/test_client/CMakeFiles/test_client.dir/rule
.PHONY : src/server/test_client/CMakeFiles/test_client.dir/rule

# Convenience name for target.
test_client: src/server/test_client/CMakeFiles/test_client.dir/rule
.PHONY : test_client

# fast build rule for target.
test_client/fast:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/build
.PHONY : test_client/fast

__/__/shared/config.o: __/__/shared/config.cpp.o
.PHONY : __/__/shared/config.o

# target to build an object file
__/__/shared/config.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/config.cpp.o
.PHONY : __/__/shared/config.cpp.o

__/__/shared/config.i: __/__/shared/config.cpp.i
.PHONY : __/__/shared/config.i

# target to preprocess a source file
__/__/shared/config.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/config.cpp.i
.PHONY : __/__/shared/config.cpp.i

__/__/shared/config.s: __/__/shared/config.cpp.s
.PHONY : __/__/shared/config.s

# target to generate assembly for a file
__/__/shared/config.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/config.cpp.s
.PHONY : __/__/shared/config.cpp.s

__/__/shared/connection/active_conn.o: __/__/shared/connection/active_conn.cpp.o
.PHONY : __/__/shared/connection/active_conn.o

# target to build an object file
__/__/shared/connection/active_conn.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/active_conn.cpp.o
.PHONY : __/__/shared/connection/active_conn.cpp.o

__/__/shared/connection/active_conn.i: __/__/shared/connection/active_conn.cpp.i
.PHONY : __/__/shared/connection/active_conn.i

# target to preprocess a source file
__/__/shared/connection/active_conn.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/active_conn.cpp.i
.PHONY : __/__/shared/connection/active_conn.cpp.i

__/__/shared/connection/active_conn.s: __/__/shared/connection/active_conn.cpp.s
.PHONY : __/__/shared/connection/active_conn.s

# target to generate assembly for a file
__/__/shared/connection/active_conn.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/active_conn.cpp.s
.PHONY : __/__/shared/connection/active_conn.cpp.s

__/__/shared/connection/connection.o: __/__/shared/connection/connection.cpp.o
.PHONY : __/__/shared/connection/connection.o

# target to build an object file
__/__/shared/connection/connection.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/connection.cpp.o
.PHONY : __/__/shared/connection/connection.cpp.o

__/__/shared/connection/connection.i: __/__/shared/connection/connection.cpp.i
.PHONY : __/__/shared/connection/connection.i

# target to preprocess a source file
__/__/shared/connection/connection.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/connection.cpp.i
.PHONY : __/__/shared/connection/connection.cpp.i

__/__/shared/connection/connection.s: __/__/shared/connection/connection.cpp.s
.PHONY : __/__/shared/connection/connection.s

# target to generate assembly for a file
__/__/shared/connection/connection.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/connection.cpp.s
.PHONY : __/__/shared/connection/connection.cpp.s

__/__/shared/connection/connection_poll.o: __/__/shared/connection/connection_poll.cpp.o
.PHONY : __/__/shared/connection/connection_poll.o

# target to build an object file
__/__/shared/connection/connection_poll.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/connection_poll.cpp.o
.PHONY : __/__/shared/connection/connection_poll.cpp.o

__/__/shared/connection/connection_poll.i: __/__/shared/connection/connection_poll.cpp.i
.PHONY : __/__/shared/connection/connection_poll.i

# target to preprocess a source file
__/__/shared/connection/connection_poll.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/connection_poll.cpp.i
.PHONY : __/__/shared/connection/connection_poll.cpp.i

__/__/shared/connection/connection_poll.s: __/__/shared/connection/connection_poll.cpp.s
.PHONY : __/__/shared/connection/connection_poll.s

# target to generate assembly for a file
__/__/shared/connection/connection_poll.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/connection_poll.cpp.s
.PHONY : __/__/shared/connection/connection_poll.cpp.s

__/__/shared/connection/passive_conn.o: __/__/shared/connection/passive_conn.cpp.o
.PHONY : __/__/shared/connection/passive_conn.o

# target to build an object file
__/__/shared/connection/passive_conn.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/passive_conn.cpp.o
.PHONY : __/__/shared/connection/passive_conn.cpp.o

__/__/shared/connection/passive_conn.i: __/__/shared/connection/passive_conn.cpp.i
.PHONY : __/__/shared/connection/passive_conn.i

# target to preprocess a source file
__/__/shared/connection/passive_conn.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/passive_conn.cpp.i
.PHONY : __/__/shared/connection/passive_conn.cpp.i

__/__/shared/connection/passive_conn.s: __/__/shared/connection/passive_conn.cpp.s
.PHONY : __/__/shared/connection/passive_conn.s

# target to generate assembly for a file
__/__/shared/connection/passive_conn.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/passive_conn.cpp.s
.PHONY : __/__/shared/connection/passive_conn.cpp.s

__/__/shared/connection/text_io.o: __/__/shared/connection/text_io.cpp.o
.PHONY : __/__/shared/connection/text_io.o

# target to build an object file
__/__/shared/connection/text_io.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/text_io.cpp.o
.PHONY : __/__/shared/connection/text_io.cpp.o

__/__/shared/connection/text_io.i: __/__/shared/connection/text_io.cpp.i
.PHONY : __/__/shared/connection/text_io.i

# target to preprocess a source file
__/__/shared/connection/text_io.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/text_io.cpp.i
.PHONY : __/__/shared/connection/text_io.cpp.i

__/__/shared/connection/text_io.s: __/__/shared/connection/text_io.cpp.s
.PHONY : __/__/shared/connection/text_io.s

# target to generate assembly for a file
__/__/shared/connection/text_io.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/text_io.cpp.s
.PHONY : __/__/shared/connection/text_io.cpp.s

__/__/shared/connection/udp_conn.o: __/__/shared/connection/udp_conn.cpp.o
.PHONY : __/__/shared/connection/udp_conn.o

# target to build an object file
__/__/shared/connection/udp_conn.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/udp_conn.cpp.o
.PHONY : __/__/shared/connection/udp_conn.cpp.o

__/__/shared/connection/udp_conn.i: __/__/shared/connection/udp_conn.cpp.i
.PHONY : __/__/shared/connection/udp_conn.i

# target to preprocess a source file
__/__/shared/connection/udp_conn.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/udp_conn.cpp.i
.PHONY : __/__/shared/connection/udp_conn.cpp.i

__/__/shared/connection/udp_conn.s: __/__/shared/connection/udp_conn.cpp.s
.PHONY : __/__/shared/connection/udp_conn.s

# target to generate assembly for a file
__/__/shared/connection/udp_conn.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/udp_conn.cpp.s
.PHONY : __/__/shared/connection/udp_conn.cpp.s

__/__/shared/connection/udp_text_io.o: __/__/shared/connection/udp_text_io.cpp.o
.PHONY : __/__/shared/connection/udp_text_io.o

# target to build an object file
__/__/shared/connection/udp_text_io.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/udp_text_io.cpp.o
.PHONY : __/__/shared/connection/udp_text_io.cpp.o

__/__/shared/connection/udp_text_io.i: __/__/shared/connection/udp_text_io.cpp.i
.PHONY : __/__/shared/connection/udp_text_io.i

# target to preprocess a source file
__/__/shared/connection/udp_text_io.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/udp_text_io.cpp.i
.PHONY : __/__/shared/connection/udp_text_io.cpp.i

__/__/shared/connection/udp_text_io.s: __/__/shared/connection/udp_text_io.cpp.s
.PHONY : __/__/shared/connection/udp_text_io.s

# target to generate assembly for a file
__/__/shared/connection/udp_text_io.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/connection/udp_text_io.cpp.s
.PHONY : __/__/shared/connection/udp_text_io.cpp.s

__/__/shared/data/text_data.o: __/__/shared/data/text_data.cpp.o
.PHONY : __/__/shared/data/text_data.o

# target to build an object file
__/__/shared/data/text_data.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/data/text_data.cpp.o
.PHONY : __/__/shared/data/text_data.cpp.o

__/__/shared/data/text_data.i: __/__/shared/data/text_data.cpp.i
.PHONY : __/__/shared/data/text_data.i

# target to preprocess a source file
__/__/shared/data/text_data.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/data/text_data.cpp.i
.PHONY : __/__/shared/data/text_data.cpp.i

__/__/shared/data/text_data.s: __/__/shared/data/text_data.cpp.s
.PHONY : __/__/shared/data/text_data.s

# target to generate assembly for a file
__/__/shared/data/text_data.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/data/text_data.cpp.s
.PHONY : __/__/shared/data/text_data.cpp.s

__/__/shared/reply.o: __/__/shared/reply.cpp.o
.PHONY : __/__/shared/reply.o

# target to build an object file
__/__/shared/reply.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/reply.cpp.o
.PHONY : __/__/shared/reply.cpp.o

__/__/shared/reply.i: __/__/shared/reply.cpp.i
.PHONY : __/__/shared/reply.i

# target to preprocess a source file
__/__/shared/reply.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/reply.cpp.i
.PHONY : __/__/shared/reply.cpp.i

__/__/shared/reply.s: __/__/shared/reply.cpp.s
.PHONY : __/__/shared/reply.s

# target to generate assembly for a file
__/__/shared/reply.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/reply.cpp.s
.PHONY : __/__/shared/reply.cpp.s

__/__/shared/request.o: __/__/shared/request.cpp.o
.PHONY : __/__/shared/request.o

# target to build an object file
__/__/shared/request.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/request.cpp.o
.PHONY : __/__/shared/request.cpp.o

__/__/shared/request.i: __/__/shared/request.cpp.i
.PHONY : __/__/shared/request.i

# target to preprocess a source file
__/__/shared/request.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/request.cpp.i
.PHONY : __/__/shared/request.cpp.i

__/__/shared/request.s: __/__/shared/request.cpp.s
.PHONY : __/__/shared/request.s

# target to generate assembly for a file
__/__/shared/request.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/request.cpp.s
.PHONY : __/__/shared/request.cpp.s

__/__/shared/server_commands.o: __/__/shared/server_commands.cpp.o
.PHONY : __/__/shared/server_commands.o

# target to build an object file
__/__/shared/server_commands.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/server_commands.cpp.o
.PHONY : __/__/shared/server_commands.cpp.o

__/__/shared/server_commands.i: __/__/shared/server_commands.cpp.i
.PHONY : __/__/shared/server_commands.i

# target to preprocess a source file
__/__/shared/server_commands.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/server_commands.cpp.i
.PHONY : __/__/shared/server_commands.cpp.i

__/__/shared/server_commands.s: __/__/shared/server_commands.cpp.s
.PHONY : __/__/shared/server_commands.s

# target to generate assembly for a file
__/__/shared/server_commands.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/server_commands.cpp.s
.PHONY : __/__/shared/server_commands.cpp.s

__/__/shared/user.o: __/__/shared/user.cpp.o
.PHONY : __/__/shared/user.o

# target to build an object file
__/__/shared/user.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/user.cpp.o
.PHONY : __/__/shared/user.cpp.o

__/__/shared/user.i: __/__/shared/user.cpp.i
.PHONY : __/__/shared/user.i

# target to preprocess a source file
__/__/shared/user.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/user.cpp.i
.PHONY : __/__/shared/user.cpp.i

__/__/shared/user.s: __/__/shared/user.cpp.s
.PHONY : __/__/shared/user.s

# target to generate assembly for a file
__/__/shared/user.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/user.cpp.s
.PHONY : __/__/shared/user.cpp.s

__/__/shared/user_awaiting.o: __/__/shared/user_awaiting.cpp.o
.PHONY : __/__/shared/user_awaiting.o

# target to build an object file
__/__/shared/user_awaiting.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/user_awaiting.cpp.o
.PHONY : __/__/shared/user_awaiting.cpp.o

__/__/shared/user_awaiting.i: __/__/shared/user_awaiting.cpp.i
.PHONY : __/__/shared/user_awaiting.i

# target to preprocess a source file
__/__/shared/user_awaiting.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/user_awaiting.cpp.i
.PHONY : __/__/shared/user_awaiting.cpp.i

__/__/shared/user_awaiting.s: __/__/shared/user_awaiting.cpp.s
.PHONY : __/__/shared/user_awaiting.s

# target to generate assembly for a file
__/__/shared/user_awaiting.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/user_awaiting.cpp.s
.PHONY : __/__/shared/user_awaiting.cpp.s

__/__/shared/user_chat.o: __/__/shared/user_chat.cpp.o
.PHONY : __/__/shared/user_chat.o

# target to build an object file
__/__/shared/user_chat.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/user_chat.cpp.o
.PHONY : __/__/shared/user_chat.cpp.o

__/__/shared/user_chat.i: __/__/shared/user_chat.cpp.i
.PHONY : __/__/shared/user_chat.i

# target to preprocess a source file
__/__/shared/user_chat.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/user_chat.cpp.i
.PHONY : __/__/shared/user_chat.cpp.i

__/__/shared/user_chat.s: __/__/shared/user_chat.cpp.s
.PHONY : __/__/shared/user_chat.s

# target to generate assembly for a file
__/__/shared/user_chat.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/user_chat.cpp.s
.PHONY : __/__/shared/user_chat.cpp.s

__/__/shared/utils/local_ip.o: __/__/shared/utils/local_ip.cpp.o
.PHONY : __/__/shared/utils/local_ip.o

# target to build an object file
__/__/shared/utils/local_ip.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/utils/local_ip.cpp.o
.PHONY : __/__/shared/utils/local_ip.cpp.o

__/__/shared/utils/local_ip.i: __/__/shared/utils/local_ip.cpp.i
.PHONY : __/__/shared/utils/local_ip.i

# target to preprocess a source file
__/__/shared/utils/local_ip.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/utils/local_ip.cpp.i
.PHONY : __/__/shared/utils/local_ip.cpp.i

__/__/shared/utils/local_ip.s: __/__/shared/utils/local_ip.cpp.s
.PHONY : __/__/shared/utils/local_ip.s

# target to generate assembly for a file
__/__/shared/utils/local_ip.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/utils/local_ip.cpp.s
.PHONY : __/__/shared/utils/local_ip.cpp.s

__/__/shared/utils/string_utils.o: __/__/shared/utils/string_utils.cpp.o
.PHONY : __/__/shared/utils/string_utils.o

# target to build an object file
__/__/shared/utils/string_utils.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/utils/string_utils.cpp.o
.PHONY : __/__/shared/utils/string_utils.cpp.o

__/__/shared/utils/string_utils.i: __/__/shared/utils/string_utils.cpp.i
.PHONY : __/__/shared/utils/string_utils.i

# target to preprocess a source file
__/__/shared/utils/string_utils.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/utils/string_utils.cpp.i
.PHONY : __/__/shared/utils/string_utils.cpp.i

__/__/shared/utils/string_utils.s: __/__/shared/utils/string_utils.cpp.s
.PHONY : __/__/shared/utils/string_utils.s

# target to generate assembly for a file
__/__/shared/utils/string_utils.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/__/__/shared/utils/string_utils.cpp.s
.PHONY : __/__/shared/utils/string_utils.cpp.s

test_client.o: test_client.cpp.o
.PHONY : test_client.o

# target to build an object file
test_client.cpp.o:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/test_client.cpp.o
.PHONY : test_client.cpp.o

test_client.i: test_client.cpp.i
.PHONY : test_client.i

# target to preprocess a source file
test_client.cpp.i:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/test_client.cpp.i
.PHONY : test_client.cpp.i

test_client.s: test_client.cpp.s
.PHONY : test_client.s

# target to generate assembly for a file
test_client.cpp.s:
	cd /home/khalil/Projects/skype && $(MAKE) $(MAKESILENT) -f src/server/test_client/CMakeFiles/test_client.dir/build.make src/server/test_client/CMakeFiles/test_client.dir/test_client.cpp.s
.PHONY : test_client.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test_client"
	@echo "... __/__/shared/config.o"
	@echo "... __/__/shared/config.i"
	@echo "... __/__/shared/config.s"
	@echo "... __/__/shared/connection/active_conn.o"
	@echo "... __/__/shared/connection/active_conn.i"
	@echo "... __/__/shared/connection/active_conn.s"
	@echo "... __/__/shared/connection/connection.o"
	@echo "... __/__/shared/connection/connection.i"
	@echo "... __/__/shared/connection/connection.s"
	@echo "... __/__/shared/connection/connection_poll.o"
	@echo "... __/__/shared/connection/connection_poll.i"
	@echo "... __/__/shared/connection/connection_poll.s"
	@echo "... __/__/shared/connection/passive_conn.o"
	@echo "... __/__/shared/connection/passive_conn.i"
	@echo "... __/__/shared/connection/passive_conn.s"
	@echo "... __/__/shared/connection/text_io.o"
	@echo "... __/__/shared/connection/text_io.i"
	@echo "... __/__/shared/connection/text_io.s"
	@echo "... __/__/shared/connection/udp_conn.o"
	@echo "... __/__/shared/connection/udp_conn.i"
	@echo "... __/__/shared/connection/udp_conn.s"
	@echo "... __/__/shared/connection/udp_text_io.o"
	@echo "... __/__/shared/connection/udp_text_io.i"
	@echo "... __/__/shared/connection/udp_text_io.s"
	@echo "... __/__/shared/data/text_data.o"
	@echo "... __/__/shared/data/text_data.i"
	@echo "... __/__/shared/data/text_data.s"
	@echo "... __/__/shared/reply.o"
	@echo "... __/__/shared/reply.i"
	@echo "... __/__/shared/reply.s"
	@echo "... __/__/shared/request.o"
	@echo "... __/__/shared/request.i"
	@echo "... __/__/shared/request.s"
	@echo "... __/__/shared/server_commands.o"
	@echo "... __/__/shared/server_commands.i"
	@echo "... __/__/shared/server_commands.s"
	@echo "... __/__/shared/user.o"
	@echo "... __/__/shared/user.i"
	@echo "... __/__/shared/user.s"
	@echo "... __/__/shared/user_awaiting.o"
	@echo "... __/__/shared/user_awaiting.i"
	@echo "... __/__/shared/user_awaiting.s"
	@echo "... __/__/shared/user_chat.o"
	@echo "... __/__/shared/user_chat.i"
	@echo "... __/__/shared/user_chat.s"
	@echo "... __/__/shared/utils/local_ip.o"
	@echo "... __/__/shared/utils/local_ip.i"
	@echo "... __/__/shared/utils/local_ip.s"
	@echo "... __/__/shared/utils/string_utils.o"
	@echo "... __/__/shared/utils/string_utils.i"
	@echo "... __/__/shared/utils/string_utils.s"
	@echo "... test_client.o"
	@echo "... test_client.i"
	@echo "... test_client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/khalil/Projects/skype && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

